kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
    name: nginx-http-scaledobject
spec:
    hosts:
    - pegasus-staging-nlb-ingress-bd116cb1ea7a4f0d.elb.us-east-2.amazonaws.com
    targetPendingRequests: 1
    scaleTargetRef:
        deployment: nginx-deployment-2
        service: nginx-service-2
        port: 80
    replicas:
        min: 0
        max: 5